version: '3.8'

services:
  nestapp:
    build: ./
    ports:
      - "3000:3001"
    env_file: 
      - ".env.development"
    depends_on:
      - henryecommerce

  henryecommerce:
    image: postgres
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ".env.development"
    

volumes:
  pgdata: