export const productsData = [
  {
    name: 'Laptop',
    description: 'High-performance laptop',
    price: 999.99,
    stock: 10,
    category: 'Electronics',
  },
  {
    name: 'Smartphone',
    description: 'Latest model smartphone',
    price: 699.99,
    stock: 25,
    category: 'Electronics',
  },
  {
    name: 'Headphones',
    description: 'Noise-cancelling headphones',
    price: 199.99,
    stock: 30,
    category: 'Electronics',
  },
  {
    name: 'Mystery Novel',
    description: 'Best-selling mystery novel',
    price: 9.99,
    stock: 100,
    category: 'Books',
  },
  {
    name: 'Sci-Fi Novel',
    description: 'Popular science fiction novel',
    price: 14.99,
    stock: 50,
    category: 'Books',
  },
  {
    name: "Men's Jacket",
    description: 'Warm winter jacket',
    price: 59.99,
    stock: 20,
    category: 'Clothing',
  },
  {
    name: "Women's Jacket",
    description: "Stylish women's jacket",
    price: 69.99,
    stock: 15,
    category: 'Clothing',
  },
  {
    name: 'Blender',
    description: 'High-speed blender',
    price: 49.99,
    stock: 40,
    category: 'Home and Kitchen',
  },
  {
    name: 'Vacuum Cleaner',
    description: 'Powerful vacuum cleaner',
    price: 129.99,
    stock: 10,
    category: 'Home and Kitchen',
  },
  {
    name: 'Action Figure',
    description: 'Collectible action figure',
    price: 19.99,
    stock: 50,
    category: 'Toys',
  },
  {
    name: 'Soccer Ball',
    description: 'Official size soccer ball',
    price: 29.99,
    stock: 25,
    category: 'Sports',
  },
  {
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat',
    price: 24.99,
    stock: 35,
    category: 'Sports',
  },
  {
    name: 'Vitamin C',
    description: 'High-dose vitamin C',
    price: 12.99,
    stock: 100,
    category: 'Health',
  },
  {
    name: 'Face Cream',
    description: 'Anti-aging face cream',
    price: 39.99,
    stock: 60,
    category: 'Beauty',
  },
  {
    name: 'Car Wax',
    description: 'High-gloss car wax',
    price: 15.99,
    stock: 20,
    category: 'Automotive',
  },
  {
    name: 'Lawn Mower',
    description: 'Electric lawn mower',
    price: 199.99,
    stock: 5,
    category: 'Garden',
  },
  {
    name: 'Drill Set',
    description: 'Comprehensive drill set',
    price: 89.99,
    stock: 15,
    category: 'Tools',
  },
  {
    name: 'Printer Paper',
    description: '500 sheets of printer paper',
    price: 6.99,
    stock: 200,
    category: 'Office Supplies',
  },
  {
    name: 'Dog Food',
    description: 'Nutritional dog food',
    price: 29.99,
    stock: 50,
    category: 'Pet Supplies',
  },
  {
    name: 'Baby Monitor',
    description: 'Video baby monitor',
    price: 79.99,
    stock: 10,
    category: 'Baby Products',
  },
];
